### ISSUE TITLE
problems with jQuery 3.0.0

### ISSUE THREAD

**Issue by techouse** [rommelsantor/jQuery-TH-Float#1]
I love this plugin, but the recent change of jQuery's v3.0.0 .offset behavior is putting this plugin out of action and prevents it from keeping the header and footer fixed while scrolling the table.

**Comment by rommelsantor** [comment]
I see the breaking change for .offset() in jQuery v3:

> When using the .offset() method, the first item in the jQuery collection must be a DOM element that has a DOM getBoundingClientRect() method. (All browsers supported by jQuery 3.0 have this API.) Any other input may result in jQuery throwing an error. Also note that the element must be visible and currently in a document (i.e., not disconnected).

Do you have an example of the issue in action?

Thanks for bringing this to my attention!

**Comment by techouse** [comment]
At the moment no. The only thing I have is enclosed in a non-public CMS and has some rather sensitive data in it so I cannot share it. :/

**Comment by rommelsantor** [comment]
No worries. At least I'm aware of it now. : ) I'll try to make some time to reproduce the issue. Can you describe how you're activating the plugin and what JS errors you're seeing?

**Comment by techouse** [comment]
I'm invoking it for the header and footer, so: `$("#stats_table").thfloat().thfloat({ side : "foot" });`
